config/routes.rb
Rails.application.routes.draw do

  resources :gear_categories

  resources :gear_pages

  resources :brands

  resources :artists

  resources :genres

  resources :video_uploads, :path => 'videos'

  get 'auth/:provider/callback', to: 'oauth_sessions#create',
        as: :oauth_sign_in
  get 'auth/failure', to: 'user_sessions#new',
        as: :oauth_fail
  get 'oauth_sessions/create'
  get 'oauth_sessions/omniauth_failure'
  get 'oauth_sessions/email_exists'
  resources :oauth_sessions, only: [:edit, :update]

  get 'welcome/landing'
  get 'welcome/normal_user'
  get 'dashboard', to: 'welcome#contributor', as: :welcome_contributor
  get 'curator', to: 'welcome#curator', as: :welcome_curator
  get 'admin', to: 'welcome#admin', as: :welcome_admin
  get 'privacy', to: 'welcome#privacy', as: :welcome_privacy
  get 'welcome/people', to: 'welcome#people', as: :welcome_people
  post '/search', to: 'welcome#search', as: :search_request
  get '/tag_search/:search_for_tag', to: 'welcome#tag_search', as: :tag_search
  get 'welcome/collections', to: 'welcome#collections', as: :welcome_collections

  get 'login', to: 'user_sessions#new'
  get 'log_in', to: 'user_sessions#new'
  get 'signin', to: 'user_sessions#new'
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
  get 'logout', to: 'user_sessions#destroy', as: :logout
  get 'account', to: 'users#show', as: :account
  get 'my_account', to: 'users#show', as: :my_account
  get 'signup', to: 'users#new', as: :signup
  get 'sign_up', to: 'users#new', as: :sign_up
  get 'register', to: 'users#new', as: :register
  get 'activate/:code', to: 'users#activate', as: :activate
  put 'change_password', to: 'users#change_password', as: :change_password
  get 'people/:url_code', to: 'users#profile', as: :profile

  namespace :api do
    post 'email_yoke', to: 'email_yoke#create'
  end

  resources :stories, controller: 'bourbon_articles'
  resources :countries
  resources :media_uploads
  get 'password_resets/token/:id', to: 'password_resets#edit'
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :pre_registrations
  resources :profile_questions
  resources :profile_question_answers, only: [:create, :update, :destroy]
  resources :profile_question_categories
  resources :users
  resources :user_content_links, only: [:create, :destroy]
  resources :user_invites
  get '/user_invite/activate/:code', to: 'user_invites#activate', as: :user_invite_activate
  get '/user_invite/re_send/:code', to: 'user_invites#re_send', as: :user_invite_re_send
  resources :user_groups
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'welcome#landing'

end

app/models/bourbon_article.rb
# == Schema Information
#
# Table name: bourbon_articles
#
#  id                   :integer          not null, primary key
#  article_title        :string(255)
#  contributor_id       :integer
#  curator_id           :integer
#  user_id              :integer
#  article_subtitle     :string(255)
#  article_published_at :datetime
#  image_id             :integer
#  article_body         :text
#  tags                 :string(255)
#  visible              :boolean
#  created_at           :datetime
#  updated_at           :datetime
#  clickable_title      :string(255)
#  ready_for_curation   :boolean          default(FALSE)
#

class BourbonArticle < ActiveRecord::Base


  # Constants

  # relationships
  belongs_to :contributor, class_name: 'User', foreign_key: :contributor_id
  belongs_to :curator, class_name: 'User', foreign_key: :curator_id
  belongs_to :image, class_name: 'MediaUpload', foreign_key: :image_id
  # has_many   :uploads, through: :bourbon_article_media_upload
  belongs_to :user
  has_many   :user_content_links
  has_one   :video_upload


  # validation
  with_options if: :ready_for_curation  do |draft|
    draft.validates :article_title, presence: true
    draft.validates :article_subtitle, presence: true
    draft.validates :article_body, presence: true
    draft.validates :article_published_at, presence: true
    #draft.validates :tags, presence: true
    draft.validates :image_id, presence: true, numericality: {only_integer: true, greater_than: 0}
  end
  validates :article_title, uniqueness: true
  validates :contributor_id, presence: true,
            numericality: {only_integer: true, greater_than: 0}
  validates :curator_id, allow_blank: true,
            numericality: {only_integer: true, greater_than: 0}
  validates :user_id, presence: true, numericality: {only_integer: true, greater_than: 0}

  # callbacks
  before_save :set_clickable_title
  before_destroy :check_dependencies

  # scopes
  scope :all_in_order, -> { order(:article_published_at, :article_title) }
  scope :published, lambda { where('visible = ? AND article_published_at < ?', true, Proc.new{Time.now}.call) }
  scope :saved_as_draft, -> { where(ready_for_curation: false) }
  scope :sent_for_review, -> { where('(visible = ? OR visible IS NULL) AND ready_for_curation = ?', false, true) }

  # class methods

  def self.search_request(search_term)
    search_result = []
    records = where('lower(article_body) LIKE :term OR lower(article_subtitle) LIKE :term OR lower(article_title) LIKE :term', term: '%' + search_term.downcase + '%')
    records.each do |x|
      search_result << {model_name: 'Bourbon Article', url: '/stories/' + x.clickable_title, name: x.article_title, description: x.article_body}
    end
    search_result
  end

  def self.tag_search_request(tag_search)
    tag_search_result = []
    records = where('lower(tags) LIKE ?', '%' + tag_search.downcase + '%')

    if records.count > 0
      records.uniq.each do |x|
        tag_search_result << {model_name: 'Bourbon Article', url: '/stories/' + x.clickable_title, name: x.article_title, description: x.article_body}
      end
    end
    tag_search_result
  end

  def self.get_by_id_or_clickable_title(requested_thing)
    where('id = ? OR clickable_title = ?', requested_thing.to_i, requested_thing.to_s).first
  end

  # instance methods

  def destroyable?
    self.user_content_links.empty? && !self.is_active?
  end

  def is_active?
    self.visible == true && self.article_published_at < Proc.new{ Time.now }.call
  end

  protected

  def set_clickable_title
    self.clickable_title = self.article_title.gsub('/', '-').gsub(':', '-').gsub('.', '-').gsub('?', '').gsub(' ','_') + "_#{self.id}"
    # The ID is added on at the end to absolutely guarantee uniqueness
  end

  def check_dependencies
    unless self.destroyable?
      errors.add(:base, "Couldn't be deleted because dependencies exist")
      false
    end
  end

end

app/controllers/bourbon_articles_controller.rb
class BourbonArticlesController < ApplicationController

  before_action :logged_in_required, except: [:index, :show]
  before_action :contributor_or_curator_required, except: [:index, :show]
  before_action :get_variables, except: [:index, :destroy]

  def index
    @bourbon_articles = BourbonArticle.published.order("created_at DESC")
    @special_body_class = 'bfm-stories-landing'
  end

  def show
    @user_content_link = UserContentLink.where(bourbon_article_id: @bourbon_article.try(:id), user_id: current_user.try(:id)).first
    @special_body_class = 'bfm-story'
  end

  def new
    @bourbon_article = BourbonArticle.new(user_id: current_user.id, contributor_id: current_user.id, article_published_at: Time.now)
    @special_body_class = 'bfm-story-form'
  end

  def edit
    @special_body_class = 'bfm-story-form'
    if @bourbon_article.is_active? && current_user && !current_user.admin? && !current_user.curator?
      flash[:error] = 'Only a Curator or Admin can edit publicly-visible articles'
      redirect_to welcome_contributor_url
    end
  end

  def create
    @bourbon_article = BourbonArticle.new(allowed_params)
    @bourbon_article.article_published_at ||= Proc.new { Time.now }.call
    @bourbon_article.user_id ||= current_user.id if current_user
    @bourbon_article.visible = false
    set_ready_for_curation
    @special_body_class = 'bfm-story-form'
    if @bourbon_article.save
      flash[:success] = 'Article was successfully created'
      redirect_to welcome_contributor_url
    else
      render action: :new
    end
  end

  def update

    @special_body_class = 'bfm-story-form'
    set_ready_for_curation
    if @bourbon_article.is_active? && current_user && !current_user.admin? && !current_user.curator?
      flash[:error] = 'Only a Curator or Admin can edit publicly-visible articles'
      redirect_to welcome_contributor_url
    elsif @bourbon_article.update_attributes(allowed_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to story_url(@bourbon_article.id)
    else
      render action: :edit
    end
  end

  def destroy
    @bourbon_article = BourbonArticle.get_by_id_or_clickable_title(params[:article_id])
    if @bourbon_article.delete
      flash[:success] = 'Article has been deleted.'
    else
      flash[:error] = 'Article could not be deleted.'
    end
    redirect_to stories_url
  end


  protected

  def get_variables
    if current_user && (current_user.admin? || current_user.curator?)
      @bourbon_article = BourbonArticle.get_by_id_or_clickable_title(params[:id])
    elsif current_user && current_user.contributor? && current_user.bourbon_articles
      @bourbon_article = current_user.bourbon_articles.get_by_id_or_clickable_title(params[:id])
    end
    @bourbon_article ||= BourbonArticle.published.get_by_id_or_clickable_title(params[:id])
    redirect_if_no_article
    @contributors = User.contributors_or_curators.all_in_order
  end

  def allowed_params
    params.require(:bourbon_article).permit(:article_title, :contributor_id, :curator_id, :article_subtitle, :article_published_at, :image_id, :article_body, :tags, :media_uploads,
                  :visible, :curator_id, :user_id, :ready_for_curation)
  end

  def set_ready_for_curation
    if params[:commit] == 'Save as draft'
      @bourbon_article.ready_for_curation = false
      @bourbon_article.visible = false
    elsif params[:commit] == 'Save and submit for Approval'
      @bourbon_article.ready_for_curation = true
      @bourbon_article.visible = false
    elsif params[:commit] == 'Approve Now'
      @bourbon_article.visible = true
    end
  end

  def redirect_if_no_article
    if @bourbon_article.nil? && params[:id].to_s.length > 0
      flash[:error] = "Sorry, couldn't find that item"
      redirect_to stories_url
      false
    end
  end

end

app/views/bourbon_articles/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-9 col-centered-packery">
      <div class="row">
      	<table border="1" style="width:100%">
		  <tr>
		  	<th>Image</th>
		    <th>Title</th>
		    <th>Subtitle</th> 
		    <th>Author</th>
		    <th>Date Updated</th>
		    <th>Review</th>
		    <th>Delete</th>
		  </tr>
		  <% @bourbon_articles.each do |bourbon_article| %>
		  <tr>
            <% if bourbon_article.image %>
		  	    <td><%= link_to(image_tag(bourbon_article.image.upload.url, :style => 'width:160px;height:120px' ), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize) %></td>
		    <% end %>
            <td><%= link_to bourbon_article.article_title.upcase.truncate(50), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize %></td>
		    <td><%= link_to(bourbon_article.article_subtitle.upcase.truncate(40), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize) %></td>
		    <td><%= link_to bourbon_article.contributor.full_name, profile_url(bourbon_article.contributor.url_code) %></td>
		    <td><%= bourbon_article.updated_at.to_s(:standard) %></td>
		    <td>
		    	<% if current_user.contributor? && bourbon_article.ready_for_curation != true %>
				  <%= link_to 'Edit', edit_story_url(bourbon_article), class: 'btn btn-default dashboard-btn' %>
				<% elsif current_user.admin? && bourbon_article.ready_for_curation && !bourbon_article.visible %>
				  <%= link_to 'Review', story_url(bourbon_article), class: 'btn btn-default dashboard-btn' %>
				<% else %>
				  <%= link_to 'View', story_url(bourbon_article), class: 'btn btn-default dashboard-btn' %>
				<% end %> 
		    </td>
		    <td>
		    	<% if bourbon_article.destroyable? %>
		    	<%= link_to 'Delete', story_url(bourbon_article), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %> 
		    	<% end %>
		    </td>
		  </tr>
		  <% end %>
		</table>
      </div>
    </div>
  </div>
</div>
      

app/views/bourbon_articles/_index.html.haml
%table.table.table-bordered.table-striped
  %tr
    %th Headline / Subtitle
    %th Author / Contributor
    %th Last updated
    %th Action
  -the_articles.each do |article|
    %tr
      %td
        =article.article_title
        %br
        %span.text-muted=article.article_subtitle
      %td
        =article.user.full_name
        -if article.user_id != article.contributor_id
          %br/
          %span.text-muted='(for ' + article.contributor.try(:full_name).to_s + ')'
      %td=article.updated_at.to_s(:standard)
      -if current_user.contributor? && article.ready_for_curation != true
        %td=link_to 'Edit', edit_story_url(article), class: 'btn btn-success btn-xs dashboard-btn'
      -elsif current_user.curator? && article.ready_for_curation && !article.visible
        %td=link_to 'Review', story_url(article), class: 'btn btn-primary btn-xs dashboard-btn'
      -else
        %td=link_to 'View', story_url(article), class: 'btn btn-info btn-xs dashboard-btn'

app/views/bourbon_articles/_old_form.html.haml
.row
  .col-md-12
    =form_for(@bourbon_article, html: {class: 'form-horizontal', role: 'form', :multipart => true }) do |f|
      .well.well-sm
        =render partial: '/layouts/error_messages', locals: {thing: @bourbon_article, message: nil}
        .form-group
          =f.label :image_id, 'Header Image', class: 'control-label col-md-2'
          .col-md-8
            =f.text_field :image_id, placeholder:'Upload a header image for your story, or choose a Bourbon image...', class: 'form-control'

        .form-group
          =f.label :article_title, class: 'control-label col-md-2'
          .col-md-8
            =f.text_field :article_title, placeholder:'Enter your title here...', class: 'form-control'
        .form-group
          =f.label :article_subtitle, 'Subtitle', class: 'control-label col-md-2'
          .col-md-8
            =f.text_area :article_subtitle, placeholder:'Add a subtitle here...', class: 'form-control'
        .form-group
          .col-md-10.col-md-offset-2
            .editable{style: 'min-height: 200px;'}=sanitize @bourbon_article.article_body, tags: %w(div p b i u strong em blockquote ul ol li h1 h2 h3), attributes: %w(style class id href alt title)
        =f.hidden_field :article_body

        .form-group
          =f.label :tags, class: 'control-label col-md-2'
          .col-md-4
            =f.text_field :tags, placeholder: 'enter tags or keywords for your story', class: 'form-control'
        .form-group
          =f.label :media_uploads, 'Uploads', class: 'control-label col-md-2'
          .col-md-4
            =f.file_field :media_uploads, placeholder: 'attach images or other files', class: 'form-control'
        -if current_user && current_user.curator?
          .form-group
            =f.label :contributor_id, 'Author name', class: 'control-label col-md-4'
            .col-md-8
              =f.collection_select :contributor_id, @contributors, :id, :full_name, {}, {prompt: 'Select...', class: 'form-control'}
          .form-group
            =f.label :article_published_at, class: 'control-label col-md-4'
            .col-md-8
              =f.datetime_select :article_published_at, class: 'form-control'

        .form-group
          .col-md-8.col-md-offset-4
            =f.submit 'Save', class: 'btn btn-success', onclick: "$('#bourbon_article_article_body').val($('.editable').html());"

:javascript
  var editor = new MediumEditor('.editable', {
    anchorInputPlaceholder: 'Type a link',
    buttons: ['bold', 'italic', 'underline', 'quote', 'orderedlist', 'unorderedlist', 'indent', 'header1', 'header2', 'paragraph'],
    targetBlank: true,
    firstHeader: 'h2',
    secondHeader: 'h3'
  });

app/views/bourbon_articles/edit.html.haml
-#.row
  .col-md-12
    .page-header
      %h1 Edit Bourbon Article

=render partial: 'form'

app/views/bourbon_articles/index.html.erb
<% if current_user.try(:contributor?) %>
  <div class="row">
    <div class="col-sm-12">
      <p>
        <%= link_to 'Write a new story', new_story_url, class: 'btn btn-success btn-sm' %>
      </p>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-9 col-centered-packery">
      <div class="row">
        <%= render :partial => "/welcome/stories_grid" %>
      </div>
    </div>
  </div>
</div>

app/views/bourbon_articles/index.html.haml
-#-if current_user.try(:contributor?)
-#  -#.row
-#    .col-sm-12
-#      %p=link_to 'Write a new story', new_story_url, class: 'btn btn-success btn-sm'
-#
-#-@bourbon_articles.each do |bourbon_article|
-#  .row
-#    .col-sm-8.col-sm-offset-2
-#      =link_to(image_tag(bourbon_article.image.try(:upload).try(:url, :large), class: 'img-responsive'), story_path(bourbon_article.clickable_title))
-#      %h3.name=link_to bourbon_article.article_title.titleize, story_path(bourbon_article.clickable_title)
-#      %p.text-muted=link_to(bourbon_article.article_subtitle.truncate(80), story_path(bourbon_article.clickable_title))
-#      %p.text-muted
-#        By
-#        =link_to user_image(bourbon_article.contributor, size: 30, class: 'img-rounded'), profile_url(bourbon_article.contributor.url_code)
-#        =link_to bourbon_article.contributor.full_name, profile_url(bourbon_article.contributor.url_code)
-#      %p=sanitize(bourbon_article.article_body.truncate(300), tags: %w(b i u strong em), attributes: %w(style class id href alt title))
-#      -if current_user
-#        %p
-#          Tags:
-#          -bourbon_article.tags.split(',').each do |tag|
-#            =link_to tag, tag_search_url(search_for_tag: tag), class: 'label label-default', title: 'search for more articles like this'

app/views/bourbon_articles/new.html.erb
<%= render partial: 'form' %>

app/views/bourbon_articles/show.html.erb
<%= content_for :jumbotron do %>
<div class="container" style="padding:0px !important;margin:0px !important;min-height:100%;width:100%">
	  <div class="jumbotron text-center" style="<%= (@bourbon_article.image ? "background: #000 url('" + @bourbon_article.image.try(:upload).try(:url).to_s + "') no-repeat !important;background-size:cover !important;" : '') + (@bourbon_article.image.try(:make_text_bright) ? 'color: #eee;' : '') %>">
	  	<div class="container article-heading-container container-no-margin">
  			<div class="bourbon_article_container show-article-padding">
			    <div class="show-article-title">
			        <%= @bourbon_article.article_title %>
			    </div>
			    <div class="show-article-subtitle">
			        <%= @bourbon_article.article_subtitle %>
			    </div>
			    <div class="show-article-author show-margin" style="<%= @bourbon_article.image.try(:make_text_bright) ? 'color: #eee;' : '' %>">
			    	<%= user_image @bourbon_article.contributor, size: 45, class: 'img-circle' %>
			    	<%= link_to @bourbon_article.contributor.full_name, profile_url(@bourbon_article.contributor.url_code), style: 'padding-left:5px;' + (@bourbon_article.image.try(:make_text_bright) ? 'color: #eee !important;' : '') %>
			    	<!-- <%#= render partial: 'shared/popover_bottom', locals: {the_title: @bourbon_article.contributor.full_name, image_url: user_image_url(@bourbon_article.contributor, size: 75)} %>
					<%# on %>
					<%#= @bourbon_article.article_published_at.to_s(:simple) %> -->
				</div>
			</div>
		</div>
	  </div>
</div>
<% end %>
	
  <div class="container container-no-margin">
  	<div class="bourbon-article-body">
    <%= @bourbon_article.article_body.html_safe %>
    </div>
  </div>

<hr/>

<% if current_user %>
  <div class="row row-no-margin">
    <div class="col-md-8 col-md-offset-2 bourbon-article-tags">
        Tags:
        <% @bourbon_article.tags.split(',').each do |tag| %>
          <%= link_to tag, tag_search_url(search_for_tag: tag), class: 'label label-default', title: 'search for more articles like this' %>
        <% end %>
    </div>
  </div>
  <div class="row row-no-margin">
    <div class="col-sm-8 col-md-offset-2 bourbon-article-recommend-bookmark">
      <%= render partial: 'user_content_links/form', locals: {thing: @bourbon_article, offer: ['recommend', 'bookmark']} %>
    </div>
  </div>
<% end %>
<% if current_user && ((current_user.id == @bourbon_article.user_id || current_user.id == @bourbon_article.contributor_id) || current_user.curator? || current_user.admin?) %>
  <div class="row row-no-margin">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table table-striped table-bordered bourbon-article-info-table">
        <tr>
          <td class="col-sm-3">
            <div class="text-muted">Approval</div>
            <%= @bourbon_article.visible ? 'Approved' : 'Not yet approved' %>
            <% if (current_user.admin? || (current_user.curator? && current_user.id != @bourbon_article.user_id)) && @bourbon_article.visible != true %>
              <%= form_for(@bourbon_article, url: story_url(@bourbon_article.id), html: {method: :put, class: 'form', role: 'form', style: 'display: inline;'}) do |f| %>
                <%= f.hidden_field :curator_id, value: current_user.id %>
                <%= f.submit 'Approve Now', class: 'btn btn-danger btn-xs', data: {confirm: 'Are you sure this article is ready for publication?'} %>
              <% end %>
            <% end %>
          </td>
          <td class="col-sm-2">
            <div class="text-muted">Visible?</div>
            <%= @bourbon_article.is_active? ? 'Visible' : 'Not visible' %>
          </td>
          <td class="col-sm-3">
            <div class="text-muted">Embargo</div>
            <%= @bourbon_article.article_published_at.to_s(:simple) %>
          </td>
          <td class="col-sm-4">
            <span class="text-muted">Writer:</span>
            <%= link_to @bourbon_article.user.try(:full_name), profile_url(@bourbon_article.user.url_code) %>
            <br/>
            <span class="text-muted">Contributor:</span>
            <% if @bourbon_article.contributor %>
              <%= link_to @bourbon_article.contributor.try(:full_name), profile_url(@bourbon_article.contributor.url_code) %>
            <% end %>
            <br/>
            <span class="text-muted">Curator:</span>
            <% if @bourbon_article.curator %>
              <%= link_to @bourbon_article.curator.try(:full_name), profile_url(@bourbon_article.curator.url_code) %>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="form-group">
        <%= link_to 'Edit', edit_story_url, class: 'btn btn-info' %> 
        <%= link_to 'Delete', { :article_id => @bourbon_article.id }, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-info' %>
        <%= link_to 'Back', stories_url, class: 'btn btn-default' %>
      </div>
      <br/>
      <br/>
      <br/>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="form-group">
        <%= link_to 'Back', stories_url, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/bourbon_articles/show.html.haml
=content_for :jumbotron do
  .jumbotron.text-center{style: (@bourbon_article.image ? "background: #fff url('" + @bourbon_article.image.try(:upload).try(:url).to_s + "') no-repeat center center !important;" : '') + (@bourbon_article.image.try(:make_text_bright) ? 'color: #eee;' : '')}
    .container
      .col-md-8.col-md-offset-2
        %h1{style: 'line-height: 1em; padding-top: 50px;'}=@bourbon_article.article_title
        %p.lead{style: 'padding: 20px 0 60px 0 !important; text-shadow: 0 2px 6px #000;'}=@bourbon_article.article_subtitle
        %p.text-muted{style: (@bourbon_article.image.try(:make_text_bright) ? 'color: #eee;' : '')}
          =user_image @bourbon_article.contributor, size: 60, class: 'img-circle'
          =link_to @bourbon_article.contributor.full_name, profile_url(@bourbon_article.contributor.url_code), style: 'text-shadow: 0 2px 6px #000; color: ' + (@bourbon_article.image.try(:make_text_bright) ? '#eee;' : '#111;')
          =#render partial: 'shared/popover_bottom', locals: {the_title: @bourbon_article.contributor.full_name, image_url: user_image_url(@bourbon_article.contributor, size: 75)}
          -#on
          =#@bourbon_article.article_published_at.to_s(:simple)

.row.bourbon-article-detail-view
  .col-md-8.col-md-offset-2
    =sanitize @bourbon_article.article_body.gsub("\r", '<br/>'), tags: %w(div p b i u strong em blockquote ul ol li h1 h2 h3), attributes: %w(style class id href alt title)

%hr/

-if current_user
  .row
    .col-md-8.col-md-offset-2
      %p
        Tags:
        -@bourbon_article.tags.split(',').each do |tag|
          =link_to tag, tag_search_url(search_for_tag: tag), class: 'label label-default', title: 'search for more articles like this'
  .row
    .col-sm-8.col-md-offset-2
      =render partial: 'user_content_links/form', locals: {thing: @bourbon_article, offer: ['recommend', 'bookmark']}

-if current_user && ((current_user.id == @bourbon_article.user_id || current_user.id == @bourbon_article.contributor_id) || current_user.curator? || current_user.admin?)
  .row
    .col-sm-8.col-sm-offset-2

      %table.table.table-striped.table-bordered
        %tr
          %td.col-sm-3
            .text-muted Approval
            =@bourbon_article.visible ? 'Approved' : 'Not yet approved'
            -if (current_user.admin? || (current_user.curator? && current_user.id != @bourbon_article.user_id)) && @bourbon_article.visible != true
              =form_for(@bourbon_article, url: story_url(@bourbon_article.id), html: {method: :put, class: 'form', role: 'form', style: 'display: inline;'}) do |f|
                =f.hidden_field :curator_id, value: current_user.id
                =f.submit 'Approve Now', class: 'btn btn-danger btn-xs', data: {confirm: 'Are you sure this article is ready for publication?'}

          %td.col-sm-2
            .text-muted Visible?
            =@bourbon_article.is_active? ? 'Visible' : 'Not visible'
          %td.col-sm-3
            .text-muted Embargo
            =@bourbon_article.article_published_at.to_s(:simple)

          %td.col-sm-4
            %span.text-muted Writer:
            =link_to @bourbon_article.user.try(:full_name), profile_url(@bourbon_article.user.url_code)
            %br/
            %span.text-muted Contributor:
            -if @bourbon_article.contributor
              =link_to @bourbon_article.contributor.try(:full_name), profile_url(@bourbon_article.contributor.url_code)
            %br/
            %span.text-muted Curator:
            -if @bourbon_article.curator
              =link_to @bourbon_article.curator.try(:full_name), profile_url(@bourbon_article.curator.url_code)
      %p
        =link_to 'Edit', edit_story_url, class: 'btn btn-success'
        or
        =link_to 'Back', welcome_contributor_url

-else
  .row
    .col-sm-8.col-sm-offset-2
      %p=link_to 'Back', root_url