config/routes.rb
Rails.application.routes.draw do

  resources :gear_categories

  resources :gear_pages

  resources :brands

  resources :artists

  resources :genres

  resources :video_uploads, :path => 'videos'

  get 'auth/:provider/callback', to: 'oauth_sessions#create',
        as: :oauth_sign_in
  get 'auth/failure', to: 'user_sessions#new',
        as: :oauth_fail
  get 'oauth_sessions/create'
  get 'oauth_sessions/omniauth_failure'
  get 'oauth_sessions/email_exists'
  resources :oauth_sessions, only: [:edit, :update]

  get 'welcome/landing'
  get 'welcome/normal_user'
  get 'dashboard', to: 'welcome#contributor', as: :welcome_contributor
  get 'curator', to: 'welcome#curator', as: :welcome_curator
  get 'admin', to: 'welcome#admin', as: :welcome_admin
  get 'privacy', to: 'welcome#privacy', as: :welcome_privacy
  get 'welcome/people', to: 'welcome#people', as: :welcome_people
  post '/search', to: 'welcome#search', as: :search_request
  get '/tag_search/:search_for_tag', to: 'welcome#tag_search', as: :tag_search
  get 'welcome/collections', to: 'welcome#collections', as: :welcome_collections

  get 'login', to: 'user_sessions#new'
  get 'log_in', to: 'user_sessions#new'
  get 'signin', to: 'user_sessions#new'
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
  get 'logout', to: 'user_sessions#destroy', as: :logout
  get 'account', to: 'users#show', as: :account
  get 'my_account', to: 'users#show', as: :my_account
  get 'signup', to: 'users#new', as: :signup
  get 'sign_up', to: 'users#new', as: :sign_up
  get 'register', to: 'users#new', as: :register
  get 'activate/:code', to: 'users#activate', as: :activate
  put 'change_password', to: 'users#change_password', as: :change_password
  get 'people/:url_code', to: 'users#profile', as: :profile

  namespace :api do
    post 'email_yoke', to: 'email_yoke#create'
  end

  resources :stories, controller: 'bourbon_articles'
  resources :countries
  resources :media_uploads
  get 'password_resets/token/:id', to: 'password_resets#edit'
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :pre_registrations
  resources :profile_questions
  resources :profile_question_answers, only: [:create, :update, :destroy]
  resources :profile_question_categories
  resources :users
  resources :user_content_links, only: [:create, :destroy]
  resources :user_invites
  get '/user_invite/activate/:code', to: 'user_invites#activate', as: :user_invite_activate
  get '/user_invite/re_send/:code', to: 'user_invites#re_send', as: :user_invite_re_send
  resources :user_groups
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'welcome#landing'

end

app/models/gear_page.rb
# == Schema Information
#
# Table name: gear_pages
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  description      :text
#  brand_id         :integer
#  artist_id        :integer
#  genre_id         :integer
#  ancestry         :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  gear_category_id :integer
#

class GearPage < ActiveRecord::Base

  # Constants

  # relationships
  belongs_to :brand
  has_and_belongs_to_many :artist
  belongs_to :genre
  # belongs_to :gear_category

  has_ancestry

  has_attached_file :profile_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :profile_image, :content_type => /\Aimage\/.*\Z/

  # validation
  #validates :name, presence: true
  #validates :description, presence: true
  #validates :brand, presence: true
  #validates :artist, presence: true
  #validates :genre, presence: true
  #validates :ancestry, presence: true

  # callbacks
  before_destroy :check_dependencies

  # scopes
  scope :all_in_order, -> { order(:name) }

  # class methods

  # instance methods
  def destroyable?
    true
  end

  protected

  def check_dependencies
    unless self.destroyable?
      errors.add(:base, "Couldn't be deleted because dependencies exist")
      false
    end
  end

end

app/controllers/gear_pages_controller.rb
class GearPagesController < ApplicationController

  AVAILABLE_METHODS = %w(index)

  before_action :logged_in_required, except: [:index, :show]
  before_action :admin_required, except: [:index, :show]
  before_action :get_variables

  def index
    # if current_user
    #   @gear_pages = current_user.gear_pages
    # else
      @gear_pages = GearPage.all_in_order
    # end
  end

  def show
    @gear_pages = GearPage.all_in_order
    @special_body_class = 'bfm-gear-show'
  end

  def new
    @gear_page = GearPage.new
    @gear_categories = GearCategory.all
  end

  def edit
   @gear_categories = GearCategory.all

  end

  def create
    @gear_page = GearPage.new(allowed_params)
    @gear_page.gear_category_id = params[:gear_category_id]
    @gear_page.user_id = current_user.id if current_user
    if @gear_page.save
      flash[:success] = 'GearPage was successfully created'
      redirect_to gear_pages_url
    else
      render action: :new
    end
  end

  def update
    if @gear_page.update_attributes(allowed_params)
      flash[:success] = 'GearPage was successfully updated'
      redirect_to gear_pages_url
    else
      render action: :edit
    end
  end

  def destroy
    if @gear_page.destroy
      flash[:success] = 'GearPage has been deleted.'
    else
      flash[:error] = 'GearPage could not be deleted.'
    end
    redirect_to gear_pages_url
  end

  private

  def get_variables
    if params[:id].to_i > 0
      @gear_page = GearPage.find(params[:id])
    end
    # @countries = Country.all_in_order
  end

  def allowed_params
    params.require(:gear_page).permit(:name, :description, :brand_id, :artist_id, :genre_id, :ancestry, :parent_id, :profile_image)
  end

end

app/helpers/gear_pages_helper.rb
module GearPagesHelper
end

app/views/gear_pages/_form.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <h1>Create a new gear page</h1>

    <%= form_for @gear_page, :html => {:multipart => true, :class => "form-horizontal"} do |f| %>
        <% if @gear_page.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@gear_page.errors.count, "error") %> prohibited this gear_page from being saved:</h2>

              <ul>
                <% @gear_page.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>



        <div class='col-md-9'>
          <div class='form-group'>
            <%= f.label :gear_category, "Select the main category:", class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%#= f.collection_select :gear_category_id, @gear_categories, :id, :name, include_blank: true, class: 'form-control' %>

              <%= f.text_field :gear_category_id, placeholder: 'main category' %>
            </div>
          </div>

          <div class='form-group'>
            <%= f.label :parent_id, "add additional categories", class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.collection_select :parent_id, GearPage.order(:name), :id, :name, include_blank: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :name, class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :name, placeholder: 'e.g. Fender Stratocaster', class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :profile_image, class: "col-md-4 control-label" %>
          <div class="col-md-8">
            <%= f.file_field :profile_image %>
            </div>
          </div>


          <div class="form-group">
            <%= f.label :description, class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.text_area :description, placeholder: 'Gear origins, description, facts etc', :size => "30x10", class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-6">
            <%= f.collection_select :genre_id, Genre.order(:name), :id, :name, include_blank: true, class: 'form-control', prompt: "Select associated genre" %>           
            </div>
            <div class="col-md-6">
              <%= link_to 'Or create a music genre', new_genre_path(@genre), target: '_blank' %>
            </div>
          </div>


          <div class="form-group">
          <div class="col-md-6">
            <%= f.collection_select :artist_id, Artist.order(:name), :id, :name, include_blank: true, multiple: true, class: 'form-control', prompt: "Select associated artist" %>  

            </div>
            <div class="col-md-6">
              <%= link_to 'Or add new artist', new_artist_path(@artist), target: '_blank' %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-6">
            <%= f.collection_select :brand_id, Brand.order(:name), :id, :name, include_blank: true, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= link_to 'add a new make/brand', new_brand_path(@brand), target: '_blank' %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-4 control-label">Where is it from?</label>

            <div class="col-sm-4">
              <select class="form-control">
                <option value="">Select a country</option>
                <option value=""></option>
                <option value="276">Australia</option>
                <option value="261">Canada</option>
                <option value="263">China</option>
                <option value="279">Denmark</option>
                <option value="267">France</option>
                <option value="265">Germany</option>
                <option value="270">India</option>
                <option value="269">Indonesia</option>
                <option value="268">Italy</option>
                <option value="262">Japan</option>
                <option value="264">Korea</option>
                <option value="260">Mexico</option>
                <option value="277">Russia</option>
                <option value="272">Spain</option>
                <option value="274">Sweden</option>
                <option value="275">Switzerland</option>
                <option value="278">Taiwan</option>
                <option value="266">United Kingdom</option>
                <option value="259">United States</option>
                <option value="271">Vietnam</option>
                <option value="273">Other</option>
              </select>
            </div>
          </div>


          <div class="actions">

            <%= f.submit class: 'btn btn-success' %>

          </div>


    <% end %>
    </div>


  </div>
</div>

app/views/gear_pages/_submenu_pages.html.erb
<ul>
	<% gear_pages.each do |gear_page, children| %>
	<li>
		<%= link_to_unless_current gear_page.name, gear_page %>
		<%= render 'submenu_pages', gear_pages: children if children.present? %>
	</li>
	<% end %>
</ul>

app/views/gear_pages/edit.html.erb
<%= render 'form' %>

app/views/gear_pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 col-centered-packery">
      <div class="row">
		
		<div id="packery-gear-container">		

			<% @gear_pages.each do |gear_page| %>
				
				<div class="packery-gear-item bourbon-packery-gear-card ">
					<div class="packery-item-overlay">
		       		    <div class="article-image-gear-container">
		                  <%= link_to (image_tag gear_page.profile_image.url(:medium)), gear_page %>
		                </div>
			    	    <div class="gear-title">
			          		<%= link_to (gear_page.name), gear_page %>
			       	    </div>
			       		<div class="gear-subtitle">
			       			<%= gear_page.description.truncate(100) %>
			       		</div>
			       		<div class="article-bookmark">
                  			<%= link_to image_tag("../assets/bookmark.png", :alt => "comments", :width => 15, :height => 20) %>
                		</div>
			        </div>
				</div>
				 
			<% end %>
				
		</div>

      </div>
    </div>
  </div>
</div>

<script>

jQuery(document).ready(function($) {
    var $container = $('#packery-gear-container');
    imagesLoaded( $container, function() {
        $container.packery({
            itemSelector: '.packery-gear-item',
 			gutter: 10,
        });
    });
});

</script>

app/views/gear_pages/new.html.erb
<%= render 'form' %>

app/views/gear_pages/show.html.erb
<div class="container" style="padding:0px !important;margin:0px !important;height:100%;width:100%">
  <div class="jumbotron jumbotron-profile" style="background: #000 url('http://sandybourbonfm.s3-eu-west-1.amazonaws.com/development/media_uploads/2/original/slider_image3.png?1424488859') no-repeat !important;background-size:cover !important;color: #eee;">
    <div class="container basic-info">
      <div class="col-sm-12 col-basic-info">
        <p class="gear-profile-image">
          <%= image_tag @gear_page.profile_image.url(:medium) %>
          <%#= user_image(@user, size: 170) %>
        </p>
        <p class="profile-name">
          <%= @gear_page.name %>
        </p>
        <div class="profile-group">
	        <p class="profile-brand">
	          <%= @gear_page.brand.try(:name) %>
	        </p>
	        <p class="profile-model">
	          Model Name
	        </p>
	        <p class="profile-description">
            <%= @gear_page.description %>
            </p> 
            <% if current_user.try(:admin?) %>
	        <p><%= link_to 'Edit', edit_gear_page_path(@gear_page) %></p>
			<p><%= link_to 'Back', gear_pages_path %></p> 
			<%end%>
	    </div>
      </div>
    </div>
  </div>
</div>


  <div class="container container-top-padding">
	<div class="col-xs-8 col-xs-offset-3 col-sm-8 col-sm-offset-3 col-lg-8 col-lg-offset-3">
      <div class="row">
      	<ul class='tabs profile-tabs'>
      	  <li><a href='#tab1'><b class="profile-counter"><i class="fa fa-info fa-info-tab"></i></b><br/>OVERVIEW</a></li>
    	  <li><a href='#tab2'><b class="profile-counter">39</b><br/>LISTINGS</a></li>
   		  <li><a href='#tab3'><b class="profile-counter">25</b><br/>STORIES</a></li>
    	  <li><a href='#tab4'><b class="profile-counter">92</b><br/>VIDEOS</a></li>
    	  <li><a href='#tab5'><b class="profile-counter">23</b><br/>COLLECTIONS</a></li>
  		</ul>
		  <div id='tab1'>
				    <div class="row">
				    	<div class=" col-xs-12 col-sm-12 col-md-12 col-width-110">
			        	    <div class="gear-show-cards">
	       						  <%= image_tag @gear_page.profile_image.url(:medium), :width => 232 %>
								  </br>
								  </br>
								  <%= @gear_page.description.truncate(100) %>
							</div>
	   						<div class="gear-show-cards">
	   							 <%= image_tag @gear_page.profile_image.url(:medium), :width => 232 %>
	   							 </br>
								 </br>
           					 	 Related Artists: <%= @gear_page.artist.try(:name) %>
	   						</div>
	   						<div class="gear-show-card-video">
	       						<%= link_to image_tag("../assets/video_still.jpg", :alt => "video", :width => 280, :height => 187) %>
								</br>
								</br>
	   						</div>
   						</div>
		      		</div>
		  </div>
		  <div id='tab2'>
		    <p>This tab will have listings.</p>
		  </div>
		  <div id='tab3'>
		    <p>This tab will have stories.</p>
		  </div>
		  <div id='tab4'>
		    <p>This tab will have videos.</p>
		  </div>
		  <div id='tab5'>
		    <p>This tab will have collections.</p>
		  </div>
      </div>
    </div>
  </div>


<!--
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%#= link_to 'people', welcome_people_url %>
    </div>
  </div>
</div> -->

<script>
	
$('ul.tabs').each(function(){
    // For each set of tabs, we want to keep track of
    // which tab is active and it's associated content
    var $active, $content, $links = $(this).find('a');

    // If the location.hash matches one of the links, use that as the active tab.
    // If no match is found, use the first link as the initial active tab.
    $active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
    $active.addClass('active');

    $content = $($active[0].hash);

    // Hide the remaining content
    $links.not($active).each(function () {
      $(this.hash).hide();
    });

    // Bind the click event handler
    $(this).on('click', 'a', function(e){
      // Make the old tab inactive.
      $active.removeClass('active');
      $content.hide();

      // Update the variables with the new link and content
      $active = $(this);
      $content = $(this.hash);

      // Make the tab active.
      $active.addClass('active');
      $content.show();

      // Prevent the anchor's default click action
      e.preventDefault();
    });
  });
</script>