config/routes.rb
Rails.application.routes.draw do

  resources :gear_categories

  resources :gear_pages

  resources :brands

  resources :artists

  resources :genres

  resources :video_uploads, :path => 'videos'

  get 'auth/:provider/callback', to: 'oauth_sessions#create',
        as: :oauth_sign_in
  get 'auth/failure', to: 'user_sessions#new',
        as: :oauth_fail
  get 'oauth_sessions/create'
  get 'oauth_sessions/omniauth_failure'
  get 'oauth_sessions/email_exists'
  resources :oauth_sessions, only: [:edit, :update]

  get 'welcome/landing'
  get 'welcome/normal_user'
  get 'dashboard', to: 'welcome#contributor', as: :welcome_contributor
  get 'curator', to: 'welcome#curator', as: :welcome_curator
  get 'admin', to: 'welcome#admin', as: :welcome_admin
  get 'privacy', to: 'welcome#privacy', as: :welcome_privacy
  get 'welcome/people', to: 'welcome#people', as: :welcome_people
  post '/search', to: 'welcome#search', as: :search_request
  get '/tag_search/:search_for_tag', to: 'welcome#tag_search', as: :tag_search
  get 'welcome/collections', to: 'welcome#collections', as: :welcome_collections

  get 'login', to: 'user_sessions#new'
  get 'log_in', to: 'user_sessions#new'
  get 'signin', to: 'user_sessions#new'
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
  get 'logout', to: 'user_sessions#destroy', as: :logout
  get 'account', to: 'users#show', as: :account
  get 'my_account', to: 'users#show', as: :my_account
  get 'signup', to: 'users#new', as: :signup
  get 'sign_up', to: 'users#new', as: :sign_up
  get 'register', to: 'users#new', as: :register
  get 'activate/:code', to: 'users#activate', as: :activate
  put 'change_password', to: 'users#change_password', as: :change_password
  get 'people/:url_code', to: 'users#profile', as: :profile

  namespace :api do
    post 'email_yoke', to: 'email_yoke#create'
  end

  resources :stories, controller: 'bourbon_articles'
  resources :countries
  resources :media_uploads
  get 'password_resets/token/:id', to: 'password_resets#edit'
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :pre_registrations
  resources :profile_questions
  resources :profile_question_answers, only: [:create, :update, :destroy]
  resources :profile_question_categories
  resources :users
  resources :user_content_links, only: [:create, :destroy]
  resources :user_invites
  get '/user_invite/activate/:code', to: 'user_invites#activate', as: :user_invite_activate
  get '/user_invite/re_send/:code', to: 'user_invites#re_send', as: :user_invite_re_send
  resources :user_groups
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'welcome#landing'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                                :integer          not null, primary key
#  first_name                        :string(255)
#  last_name                         :string(255)
#  email                             :string(255)
#  country_id                        :integer
#  latitude                          :float
#  longitude                         :float
#  time_zone                         :string(255)
#  user_group_id                     :integer
#  active                            :boolean          default(FALSE), not null
#  blocked                           :boolean          default(FALSE), not null
#  activation_code                   :string(255)
#  activated_at                      :datetime
#  blocked_by                        :integer
#  password_reset_token              :string(255)
#  password_reset_token_requested_at :datetime
#  password_reset_at                 :datetime
#  crypted_password                  :string(255)      default(""), not null
#  password_salt                     :string(255)      default(""), not null
#  perishable_token                  :string(255)      default("")
#  persistence_token                 :string(255)
#  single_access_token               :string(255)
#  login_count                       :integer          default(0)
#  failed_login_count                :integer          default(0)
#  last_request_at                   :datetime
#  current_login_at                  :datetime
#  last_login_at                     :datetime
#  current_login_ip                  :string(255)
#  last_login_ip                     :string(255)
#  allow_email_alerts                :boolean          default(FALSE)
#  url_code                          :string(255)
#  created_at                        :datetime
#  updated_at                        :datetime
#  remaining_invites                 :integer          default(0)
#  tags                              :string(255)
#  location                          :string(255)
#

class User < ActiveRecord::Base


  # relationships
  has_many   :bourbon_articles # as the writer
  has_many   :gear_pages # as the writer
  has_many   :bourbon_articles_contributed, class_name: 'BourbonArticle',
              foreign_key: :contributor_id
  has_many   :bourbon_articles_curated, class_name: 'BourbonArticle',
              foreign_key: :curator_id
  belongs_to :country
  has_many   :incoming_content_links,
              class_name: 'UserContentLink',
              foreign_key: :profile_id
  has_many   :omniauth_authorizations
  has_many   :profile_question_answers
  has_many   :user_content_links
  has_many   :user_invites
  belongs_to :user_group

  geocoded_by :current_login_ip

  acts_as_authentic do |c|
    if Rails.env.production? || Rails.env.staging?
      c.logged_in_timeout = 30.days
    else
      c.logged_in_timeout = 120.minutes
    end
    # extra code in app/models/user_session.rb makes this enforceable ONLY on admins
  end

  # validation
  validates :email, presence: true, uniqueness: true,
            length: {within: 7..40}, # todo: ,
            format: {with:  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      message: 'must be a valid email address.'}
  validates :first_name, presence: true, length: {within: 2..30}
  validates :last_name, presence: true, length: {within: 2..30}
  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :password, allow_nil: true, allow_blank: true, length: {minimum: 6}, on: :update
  validates_confirmation_of :password, unless: 'password.blank?'
  validates :user_group_id,
            inclusion: {in: Proc.new { UserGroup.full_list_of_ids} }
  validates :country_id, presence: true,
            numericality: {only_integer: true, greater_than: 0}
  validates :time_zone, presence: true

  # callbacks
  before_create :set_url_code
  before_create :grant_user_invites
  before_create :geocode, if: :current_login_ip_changed?
  before_destroy :check_dependencies

  # scopes

  scope :all_in_order, -> { order(:user_group_id, :last_name, :first_name) }

  # instance methods
  def admin?
    self.user_group.is_admin
  end

  def change_password(current, new_password, confirmation)
    if self.valid_password?(current) && new_password == confirmation && new_password.length > 5
      self.password = new_password
      self.password_confirmation = confirmation
      self.save
    else
      false
    end
  end

  def consume_one_invite_credit
    if self.user_group.limit_user_invites_for_this_group
      if self.remaining_invites > 0
        self.remaining_invites -= 1
        self.save!
      else
        Rails.logger.error "User.consume_one_invite_credit: User ##{self.id} sent an unauthorised invite: current balance #{self.remaining_invites}."
      end
    end
  end

  def contributor?
    self.user_group.is_contributor
  end

  def curator?
    self.user_group.is_curator
  end

  def destroyable?
    false
  end 

  def full_name
    self.first_name.titleize + ' ' + self.last_name.gsub('O\'','O\' ').titleize.gsub('O\' ','O\'')
  end

  def gravatar_url(the_size=100)
    # gravatar_id = Digest::MD5::hexdigest(self.login).downcase
    # 'http://gravatar.com/avatar/' + gravatar_id + '.png'
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://gravatar.com/avatar/#{hash}?size=#{the_size}"
  end

  # class methods

  def self.activate_with_code(the_code)
    user = User.where(activation_code: the_code).first
    if user
      user.activation_code = nil
      user.active = true
      unless user.save
        Rails.logger.warn 'User.activate_with_code failed to save: ' + user.inspect
      end
      user
    else
      false
    end
  end

  def self.contributors_or_curators
    includes(:user_group).where('user_groups.is_contributor = ? or user_groups.is_curator = ?', true, true).references(:user_group)
  end

  def self.list_of_ids
    User.all.map(&:id)
  end

  def self.search_request(user_search)
    search_result = []
    records = User.where('lower(first_name) LIKE :s or lower(last_name) LIKE :s', s: '%' + user_search.downcase + '%')

    if records.count > 0
      records.uniq.each do |x|
        search_result << {model_name: 'User', url: '/profile/' + x.url_code, name: x.full_name, description: x.full_name + ' is the search result'}
      end
    end
    search_result
  end

  def self.with_url_code(the_url_code)
    where(url_code: the_url_code).first
  end

  # password reset processing - step 1
  def self.send_password_reset(email_address)
    user = User.where(email: email_address).first
    if user
      user.password_reset_token = ApplicationController.generate_random_code(20)
      user.password_reset_token_requested_at = Time.now
      user.crypted_password = 'locked'
      user.active = false
      user.save!
      UserMailer.reset_your_password(user).deliver
    end
  end

  # password reset processing - step 2 and 3
  def self.validate_password_reset_code(the_code)
    User.where(active: false, password_reset_token: the_code).first
  end

  # password reset processing - step 4
  def reset_password_with_code(the_code, new_password_1, new_password_2)
    if self.id == User.validate_password_reset_code(the_code.to_s).try(:id)
      self.password_reset_token = nil
      self.active = true
      self.password = new_password_1.to_s
      self.password_confirmation = new_password_2.to_s
      if self.save
        return self
      else
        Rails.logger.warn 'User.reset_password_with_code failed to save: ' + self.inspect
        return nil
      end
    else
      Rails.logger.warn 'User.reset_password_with_code failed to find a user: ' + the_code.to_s
      return nil
    end
  end

  def self.tagged_with(a_tag)
    where('tags LIKE ?', '%' + a_tag + '%')
  end

  protected

  def check_dependencies
    unless self.destroyable?
      errors.add(:base, "Couldn't be deleted because dependencies exist")
      false
    end
  end

  def grant_user_invites
    if self.user_group.try(:limit_user_invites_for_this_group)
      self.remaining_invites = self.user_group.invites_limit_per_user
    else
      self.remaining_invites = 0
    end
  end

  def set_url_code
    self.url_code = ApplicationController.generate_random_code(20)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_required, except: [:new, :create, :activate]
  before_action :logged_out_required, only: :activate
  before_action :admin_required, except: [:show, :edit, :update, :profile, :change_password, :new, :create, :activate]
  before_action :get_variables

  def index
    @users = User.paginate(page: params[:page], per_page: 50).all_in_order
  end

  def show
  end

  def profile
    # requires params[:url_code] to match @user.url_code
    @bourbon_articles = BourbonArticle.published.all_in_order
    @user = User.with_url_code(params[:url_code])
    @user_content_link = current_user.user_content_links.where(profile_id: @user.id).first
    @special_body_class = 'bfm-profile'
  end

  def new
    if !current_user || (current_user && current_user.admin?)
      @user = User.new
      #country_name = @location[:country_name]
      #@user.country_id = Country.named(country_name).try(:id) if country_name && country_name != 'Reserved'
      @user.country_id = Country.named('Ireland').id # todo
      @user.time_zone = Time.zone.name # todo:
      @user.allow_email_alerts = true
    else
      flash[:error] = 'You are not permitted to do that [U01]'
      redirect_to root_url
    end
    @special_body_class = 'bfm-sign-up'
  end

  def edit
  end

  def create
    if !current_user || (current_user && current_user.admin?)
      @user = User.new(allowed_params)
      @user.active = false
      @user.activation_code = ApplicationController.generate_random_code(20)
      @user.user_group_id = UserGroup.default_group.id
      if @user.save
        if params[:user_invite_activation_code].to_s == ''
          UserMailer.confirm_your_registration(@user).deliver
          flash[:success] = 'Your user ID has been created. Please check your email for further instructions.'
        else
          if UserInvite.activated_by_new_user(@user.id, params[:user_invite_activation_code])
            @user.update_attributes(active: true)
            UserSession.create(@user)
            flash[:success] = 'Your invite has been successfully turned into a full user account. Welcome to Bourbon!'
          else
            flash[:error] = 'Something went wrong with your invite, but your user ID has been created anyway. Please check your email for further instructions'
            Rails.logger.error "Bourbon UsersController#create: UserInvite activated incorrectly: @user = #{@user.inspect}. Invitation Code: #{params[:user_invite_activation_code].to_s}"
          end
        end
        redirect_to root_url
      else
        if params[:user_invite_activation_code].to_s == ''
          render action: 'new'
        else
          flash[:error] = 'Your new profile could not be created for the following reasons: ' + @user.errors.full_messages.to_sentence
          redirect_to user_invite_activate_url(code: params[:user_invite_activation_code])
        end
      end
    else
      flash[:error] = 'You are not permitted to do that [U01]'
      redirect_to root_url
    end
  end

  def update
    # @user has already been conditionally set in 'get_variables'
    if @user.update_attributes(allowed_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to @user
    else
      render action: 'edit'
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = 'User has been successfully deleted'
    else
      flash[:error] = 'User could not be deleted (U-01)'
    end
    redirect_to users_url
  end

  def change_password
    # assumes params {password, password_confirmation, current_password}
    if current_user.change_password(params[:user][:current_password], params[:user][:password], params[:user][:password_confirmation])
      flash[:success] = 'Your password has been successfully changed'
    else
      flash[:error] = 'Your password was not changed'
    end
    redirect_to my_account_url
  end

  def activate
    if params[:code]
      user = User.activate_with_code(params[:code].to_s)
      if user
        UserSession.create(user)
        flash[:success] = 'Your account has been activated!'
      else
        flash[:error] = 'Your activation failed. Try again or contact us for help. [U-02]'
      end
    else
      flash[:error] = 'Activation failed. (U-03)'
    end
    redirect_to root_url
  end

  protected

  def get_variables
    @countries = Country.all_in_order
    @user_groups = UserGroup.all_in_order
    # todo: @countries = Country.all_in_order
    if params[:id].to_i > 0 && current_user && current_user.admin?
      @user = User.find(params[:id])
    elsif current_user
      @user = current_user
    else
      @user = nil
    end
    @special_body_class = 'bfm-no-jumbotron' # might get over-written in individual methods
  end

  def allowed_params
    if current_user && current_user.admin?
      params.require(:user).permit(:active, :country_id, :current_login_at, :current_login_ip,
                                   :failed_login_count, :first_name, :last_login_at,
                                   :last_login_ip, :last_name, :last_request_at, :email,
                                   :login_count, :password, :password_confirmation,
                                   :user_group_id, :time_zone, :tags, :location,
                                   :active)
    else
      params.require(:user).permit(:active, :country_id, :current_login_at, :current_login_ip,
                                   :failed_login_count, :first_name, :last_login_at,
                                   :last_login_ip, :last_name, :last_request_at, :email,
                                   :login_count, :password, :password_confirmation,
                                   :user_group_id, :time_zone, :tags, :location)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_image(user, size: 100, **options)
    image_tag user_image_url(user, size: size), options
  end

  def user_image_url(user, size: 100)
    authorization = user.omniauth_authorizations.most_recent.first

    if authorization && authorization.provider == "facebook"
      facebook_picture_url authorization.uid, size
    else
      user.gravatar_url(size)
    end
  end

  def facebook_picture_url(uid, size)
    "https://graph.facebook.com/#{uid}/picture?height=#{size}&width=#{size}"
  end

end

app/views/users/_avatar_block.html.haml
-# This will only work if you send in a local variable called "owned_thing"
.row
  .col-md-12
    .hidden-xs
      =image_tag owned_thing.user.avatar_url
    %p.text-muted
      -if owned_thing.created_at
        -if owned_thing.user_id == current_user.id
          You contributed this on
          =owned_thing.created_at.to_s(:standard)
        -else
          =link_to owned_thing.user.full_name, user_url(owned_thing.user.url_code), target: '_blank'
          at
          =owned_thing.created_at.to_s(:standard)
      -else
        =owned_thing.user.full_name

app/views/users/_change_password.html.haml
.row
  .col-md-8.col-md-offset-2
    =form_for @user, url: change_password_url, html: {method: :put, class: 'form-horizontal', role: 'form'} do |f|
      =render partial: 'layouts/error_messages', locals: {thing: @user, message: nil}
      .form-group
        =f.label :password, 'New password', class: 'control-label col-sm-4'
        .col-md-8
          =f.password_field :password, autofocus: true, class: 'form-control'
      .form-group
        =f.label :password_confirmation, 'Enter it again', class: 'control-label col-sm-4'
        .col-md-8
          =f.password_field :password_confirmation, class: 'form-control'
      .form-group
        =f.label :current_password, class: 'control-label col-sm-4'
        .col-md-8
          =f.password_field :current_password, class: 'form-control'
      .form-group
        .col-md-8.col-md-offset-4
          =f.submit 'Save', class: 'btn btn-success'

app/views/users/_form.html.erb
<div class="row row-no-margin">
    <div class="col-xs-12 offset col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
    <%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
      <% if !@user_invite.nil? %>
        <%= hidden_field_tag :user_invite_activation_code, @user_invite.activation_code %>
      <% end %>
      <%= render partial: 'layouts/error_messages', locals: {thing: @user, message: nil} %>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.text_field :first_name, placeholder: 'Jay', autofocus: true, class: 'form-control', required: true %>
        </div>
        <%= f.label :first_name, class: 'control-label col-sm-4' %>
      </div>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.text_field :last_name, placeholder: 'Dee', class: 'form-control', required: true %>
        </div>
        <%= f.label :last_name, class: 'control-label col-sm-4' %>
      </div>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.email_field :email, placeholder: 'jaydee@example.com', class: 'form-control', readonly: !@user_invite.nil?, required: @user_invite.nil? %>
        </div>
        <%= f.label :email, class: 'control-label col-sm-4' %>
      </div>
      <% if !current_user || (current_user && current_user.admin?) %>
        <div class="form-group register-form-group">
          <div class="col-sm-8 col-md-8">
            <%= f.password_field :password, placeholder: '******', class: 'form-control' %>
          </div>
          <%= f.label :password, class: 'control-label col-sm-4' %>
        </div>
        <div class="form-group register-form-group">
          <div class="col-sm-8 col-md-8">
            <%= f.password_field :password_confirmation, placeholder: '******', class: 'form-control' %>
          </div>
          <%= f.label :password_confirmation, class: 'control-label col-sm-4' %>
        </div>
      <% end %>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.collection_select :country_id, @countries, :id, :name, {}, class: 'form-control' %>
        </div>
        <%= f.label :country_id, class: 'control-label col-sm-4' %>
      </div>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.text_field :location, placeholder: 'London, Tallin, Orange County, wherever you are', class: 'form-control', required: true %>
        </div>
        <%= f.label :location, class: 'control-label col-sm-4' %>
      </div>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.time_zone_select :time_zone, nil, {}, class: 'form-control' %>
        </div>
        <%= f.label :time_zone, class: 'control-label col-sm-4' %>
      </div>
      <div class="form-group register-form-group">
        <div class="col-sm-8 col-md-8">
          <%= f.text_field :tags, placeholder: 'Guitar, piano, singer, songwriter', class: 'form-control', required: true %>
        </div>
        <%= f.label :tags, class: 'control-label col-sm-4' %>
      </div>
      <% if current_user && current_user.admin? %>
        <div class="form-group register-form-group">
          <div class="col-sm-8 col-md-8">
            <%= f.collection_select :user_group_id, @user_groups, :id, :name, {}, {class: 'form-control'} %>
          </div>
          <%= f.label :user_group_id, class: 'control-label col-sm-4' %>
        </div>
        <div class="form-group register-form-group">
            <div class="checkbox">
              <%= f.label :active %>
              <%= f.check_box :active %>
            </div>
        </div>
      <% end %>
      <div class="col-sm-8 col-md-8">
      <div class="form-group email-alerts">
          <%= f.check_box :allow_email_alerts %>
          <%= f.label :allow_email_alerts, style:'font-weight:200 !important;' %>
      </div>
      <div class="form-group" style="width: 414px !important;">
          <%= f.submit 'Save', class: 'btn btn-success' %>
          <%= link_to 'Sign up using your Facebook ID', '/auth/facebook', id: 'fb_sign_in', class: 'btn btn-primary btn-facebook', target: '_top' %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.haml
.row
  .col-xs-12.col-sm-4.col-sm-offset-4.col-md-4.col-md-offset-4
    .page-header
      %h1 Edit User Profile

=render 'form'
.row
  .col-xs-12.col-sm-4.col-sm-offset-4.col-md-4.col-md-offset-4
    %p
      -if current_user.try(:admin?)
        =link_to 'Back', users_url
      -else
        =link_to 'Back', root_url
      \|
      =link_to 'View Profile', @user

app/views/users/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Users
.row
  .col-md-12
    =will_paginate @users, renderer: BootstrapPagination::Rails
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th Email / Name
          %th Active
          %th Country
          %th Actions
      %tbody
        -tracker = 0
        -@users.each do |user|
          -if tracker != user.user_group_id
            -tracker = user.user_group_id
            %tr
              %td{colspan: 4}
                %h4=link_to user.user_group.name, user.user_group
          %tr
            %td
              =link_to user.email, user_path(user)
              %br= user.full_name
            %td= user.active ? 'Yes' : 'No'
            %td=# todo: user.country.name
            %td
              =link_to 'Profile', profile_path(user.url_code)
              =link_to 'Edit', edit_user_path(user), class: 'btn btn-xs btn-info'
              -if user.destroyable?
                =link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-xs btn-danger'
    =link_to 'New', new_user_path, class: 'btn btn-primary'
    or manage
    =link_to 'user groups', user_groups_url

app/views/users/new.html.erb
<div class="row row-no-margin">
  <div class="col-xs-12 offset col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
    <div class="signin-form">
      Sign up
    </div>
  </div>
</div>
<%= render 'form' %>
</div>

app/views/users/new.html.haml
.row
  .col-md-12
    .page-header
      %h1 Sign up
= render 'form'

.row
  .col-md-8.col-md-offset-2
    .row
      .col-md-8.col-md-offset-4
        =link_to 'Sign up using your Facebook ID', '/auth/facebook', id: 'fb_sign_in', class: 'btn btn-primary', target: '_top'

.row
  .col-md-12
    %p
      -if current_user && current_user.admin?
        =link_to 'Back', users_path
      -else
        =link_to 'Back', root_url

app/views/users/show.html.haml
.row
  .col-md-12
    .page-header
      %h1
        User
        =@user.id
.row
  .col-md-12
    %table.table.table-bordered.table-striped
      %tr
        %th Name:
        %td=@user.full_name
      %tr
        %th Email:
        %td=@user.email
      %tr
        %th Country:
        %td
          -if current_user.admin?
            =link_to @user.country.try(:name), @user.try(:country) || '#'
          -else
            =@user.country.try(:name)
      %tr
        %th Location:
        %td=@user.location
      %tr
        %th Time Zone:
        %td=@user.time_zone
      %tr
        %th Tags:
        %td
          -@user.tags.to_s.split(',').each do |tag|
            =link_to(tag.strip, welcome_people_url(tag: tag.strip), title: 'See people that use this tag', class: 'btn btn-xs btn-success')
      %tr
        %th User group:
        %td
          -if current_user.admin?
            =link_to @user.user_group.name, @user.user_group
          -else
            =@user.user_group.name
      %tr
        %th Active:
        %td=@user.active ? 'Yes' : 'No'
      %tr
        %th Allow email alerts:
        %td=@user.allow_email_alerts ? 'Yes' : 'No'
      %tr
        %th Url code (to your public profile):
        %td=link_to @user.url_code, profile_url(url_code: @user.url_code)
      %tr
        %th Registered:
        %td=@user.created_at.to_s(:standard)
      %tr
        %th Invites to new users:
        %td
          =@user.user_group.limit_user_invites_for_this_group ? "You have #{pluralize(@user.remaining_invites, 'invites')} left" : 'Unlimited invites'
          -@user.user_invites.each do |invite|
            %br/
            -if invite.closed?
              =link_to invite.invitee_user.full_name, profile_url(invite.invitee_user.url_code), title: "click to view the user's Bourbon profile"
            -elsif invite.stale?
              .text-muted{title: 'Their invite has expired'}=invite.email
            -elsif invite.still_open?
              =invite.first_name + ' (' + invite.email + ')'
              -if invite.emails_sent < 3
                =link_to 're-send', user_invite_re_send_url(invite.activation_code)
          -if !@user.user_group.limit_user_invites_for_this_group || @user.remaining_invites > 0
            %br/
            -@user_invite = UserInvite.new(user_id: @user.id)
            =render partial: 'shared/modal_wrapper', locals: {the_form: 'user_invites/form', btn_label: 'Send a New Invite', target_id: 'new_invite_modal', public_title: 'Invite a friend to Bourbon'}

    -if current_user.id == @user.id
      %p=render partial: 'shared/modal_wrapper', locals: {the_form: 'users/change_password', btn_label: 'Change Password', target_id: "password_modal_#{@user.id}", public_title: 'Change Your Password'}

  .col-md-12
    %p
      -if current_user.admin?
        =link_to 'Back', users_path
      -else
        =link_to 'Back', root_url
      \|
      =link_to 'Edit', edit_user_path(@user)