config/routes.rb
Rails.application.routes.draw do

  resources :gear_categories

  resources :gear_pages

  resources :brands

  resources :artists

  resources :genres

  resources :video_uploads, :path => 'videos'

  get 'auth/:provider/callback', to: 'oauth_sessions#create',
        as: :oauth_sign_in
  get 'auth/failure', to: 'user_sessions#new',
        as: :oauth_fail
  get 'oauth_sessions/create'
  get 'oauth_sessions/omniauth_failure'
  get 'oauth_sessions/email_exists'
  resources :oauth_sessions, only: [:edit, :update]

  get 'welcome/landing'
  get 'welcome/normal_user'
  get 'dashboard', to: 'welcome#contributor', as: :welcome_contributor
  get 'curator', to: 'welcome#curator', as: :welcome_curator
  get 'admin', to: 'welcome#admin', as: :welcome_admin
  get 'privacy', to: 'welcome#privacy', as: :welcome_privacy
  get 'welcome/people', to: 'welcome#people', as: :welcome_people
  post '/search', to: 'welcome#search', as: :search_request
  get '/tag_search/:search_for_tag', to: 'welcome#tag_search', as: :tag_search
  get 'welcome/collections', to: 'welcome#collections', as: :welcome_collections

  get 'login', to: 'user_sessions#new'
  get 'log_in', to: 'user_sessions#new'
  get 'signin', to: 'user_sessions#new'
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
  get 'logout', to: 'user_sessions#destroy', as: :logout
  get 'account', to: 'users#show', as: :account
  get 'my_account', to: 'users#show', as: :my_account
  get 'signup', to: 'users#new', as: :signup
  get 'sign_up', to: 'users#new', as: :sign_up
  get 'register', to: 'users#new', as: :register
  get 'activate/:code', to: 'users#activate', as: :activate
  put 'change_password', to: 'users#change_password', as: :change_password
  get 'people/:url_code', to: 'users#profile', as: :profile

  namespace :api do
    post 'email_yoke', to: 'email_yoke#create'
  end

  resources :stories, controller: 'bourbon_articles'
  resources :countries
  resources :media_uploads
  get 'password_resets/token/:id', to: 'password_resets#edit'
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :pre_registrations
  resources :profile_questions
  resources :profile_question_answers, only: [:create, :update, :destroy]
  resources :profile_question_categories
  resources :users
  resources :user_content_links, only: [:create, :destroy]
  resources :user_invites
  get '/user_invite/activate/:code', to: 'user_invites#activate', as: :user_invite_activate
  get '/user_invite/re_send/:code', to: 'user_invites#re_send', as: :user_invite_re_send
  resources :user_groups
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'welcome#landing'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  #before_filter :re_route, only: :landing
  protect_from_forgery except: :landing
  before_filter :logged_in_required, except: [:landing, :privacy]
  before_filter :contributor_required, only: :contributor
  before_filter :curator_required, only: :curator
  before_filter :admin_required, only: :admin

  def landing
    @bourbon_articles = BourbonArticle.published.order("created_at DESC").limit(14)
    @videos = VideoUpload.order("created_at DESC").limit(9)
    @users = User.all_in_order
    @special_body_class = 'bfm-homepage'
  end

  def normal_user
    @bourbon_articles = BourbonArticle.published.all_in_order
  end

  def contributor
    @bourbon_articles = current_user.admin? ?
        BourbonArticle.all :
        BourbonArticle.where('user_id = :user OR contributor_id = :user', user: current_user.id)
        # current_user.bourbon_articles.all
    @special_body_class = 'bfm-no-jumbotron'
    @videos = VideoUpload.all
    @curated_articles = BourbonArticle.sent_for_review
  end

  def curator
    @bourbon_articles = BourbonArticle.sent_for_review
    @special_body_class = 'bfm-no-jumbotron'
  end

  def admin
    @user_all = User.all.count
    @media_uploads_all = MediaUpload.all.count
    @bourbon_articles_all = BourbonArticle.all.count
    @special_body_class = 'bfm-no-jumbotron'
  end

  def search
    search_models = [User, BourbonArticle]
    @search_results = []
    search_models.each do |a_model|
      @search_results += a_model.search_request(params[:search_for_this])
    end
  end

  def destroy
   if @bourbon_article.destroy
    flash[:success] = 'Article has been deleted.'
  else
    flash[:error] = 'Article could not be deleted.'
  end
  redirect_to stories_url
end


  def tag_search
    tag_search_models = [BourbonArticle]
    @tag_search_results = []
    tag_search_models.each do |a_model|
      @tag_search_results += a_model.tag_search_request(params[:search_for_tag])
    end
    @tag_search_results
  end

  def people
    if params[:tag].to_s.length > 0
      @users = User.tagged_with(params[:tag].to_s)
    else
      @users = User.all
    end
    @special_body_class = 'bfm-no-jumbotron'
  end

  def collections
    @users = User.all
  end

  def privacy
  end

  protected

  def re_route
    unless params[:force] == 'yes'
      if current_user.try(:admin?)
        redirect_to action: :admin
      elsif current_user.try(:curator?)
        redirect_to action: :curator
      elsif current_user.try(:contributor?)
        redirect_to action: :contributor
      elsif current_user
        redirect_to action: :normal_user
      end
      return false
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_stories_grid.html.erb
<% col_counter = 0 %>
<% row_counter = 0 %>
<% col_width = 5 %>
<% @bourbon_articles.each do |bourbon_article| %>
  <% if col_counter >= 12 %>
    <%= "</div><div class='row'>".html_safe %>
    <% col_counter = 0 %>
    <% row_counter += 1 %>
    <% col_width = row_counter.even? ? 7 : 5 %>
  <% else %>
    <% col_width = (col_width == 7 ? 5 : 7) %>
  <% end %>
  <% col_counter += col_width %>
<% end %>
<!-- PACKERY ------------------------------------------------------------->

<div id="packery-container">

		
	<% @bourbon_articles.each do |bourbon_article| %>
		
		<div class="packery-item bourbon-packery-card ">
			<div class="packery-item-overlay">
			    <div class="author-name">
	                <%= link_to user_image(bourbon_article.contributor, size: 15, class: 'img-circle'), profile_url(bourbon_article.contributor.url_code) %>
	                <%= link_to bourbon_article.contributor.full_name, profile_url(bourbon_article.contributor.url_code) %>
       		    </div>
                <% if bourbon_article.image %>	
                	<%= link_to story_path(bourbon_article.clickable_title) do %>
					  <div class="article-image-container" style="<%= ("background: url('" + bourbon_article.image.try(:upload).try(:url).to_s + "') no-repeat center center !important;background-size:cover !important;") %>"> 
					  </div>
					<% end %>
				<% end %>					
	    	    <div class="article-title ">
	          		<%= link_to bourbon_article.article_title.upcase.truncate(80), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize, class:'title-color' %>
	       	    </div>
	       		<div class="article-subtitle">
	       			<%= link_to(bourbon_article.article_subtitle.upcase.truncate(60), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize, class:'subtitle-color') %>
	       		</div>
	       	<!--<div class="article-comments">
	       			<% comment_number = ['12', '5', '8', '19', '21', '3', '17'] %>
	      			<%= link_to image_tag("../assets/comment_bubble.png", :alt => "comments", :width => 30, :height => 30) %> <%= comment_number.sample %>
	      		</div>
	      		<div class="article-bookmark">
	        		<%= link_to image_tag("../assets/bookmark.png", :alt => "comments", :width => 15, :height => 20) %>
	        </div>-->
	        </div>
		</div>
		 
	<% end %>
		
</div>

<script>

jQuery(document).ready(function($) {
    var $container = $('#packery-container');
    imagesLoaded( $container, function() {
        $container.packery({
            itemSelector: '.packery-item',
 			gutter: 10,
        });
    });
});

</script>

app/views/welcome/_stories_grid.html.haml
-col_counter = 0
-row_counter = 0
-col_width = 5

-bourbon_articles.each do |bourbon_article|
  -if col_counter >= 12
    ="</div><div class='row'>".html_safe
    -col_counter = 0
    -row_counter += 1
    -col_width = row_counter.even? ? 7 : 5
  -else
    -col_width = (col_width == 7 ? 5 : 7)
  -col_counter += col_width
  .bourbon-article-mini-view{class: "col-sm-#{col_width}"}
    .row
      -if bourbon_article.image
        =link_to(image_tag(bourbon_article.image.upload.url("story_mini_view_#{col_width}".to_sym), class: 'col-sm-12'), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize)

      .col-sm-12
        %h3.name=link_to bourbon_article.article_title.titleize.truncate(80), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize
        %p.text-muted{style: 'margin-bottom: -5px !important;'}=link_to(bourbon_article.article_subtitle.truncate(50), story_path(bourbon_article.clickable_title), title: bourbon_article.article_title.titleize)
        %h3.author-name
          =link_to user_image(bourbon_article.contributor, size: 30, class: 'img-circle'), profile_url(bourbon_article.contributor.url_code)
          =link_to bourbon_article.contributor.full_name, profile_url(bourbon_article.contributor.url_code)
      -#if current_user
        %p
          Tags:
          -bourbon_article.tags.split(',').each do |tag|
            =link_to tag, tag_search_url(search_for_tag: tag), class: 'label label-default', title: 'search for more articles like this'

app/views/welcome/_videos_grid.html.erb
<% col_counter = 0 %>
<% row_counter = 0 %>
<% col_width = 5 %>
<% @videos.each do |video| %>
  <% if col_counter >= 12 %>
    <%= "</div><div class='row'>".html_safe %>
    <% col_counter = 0 %>
    <% row_counter += 1 %>
    <% col_width = row_counter.even? ? 7 : 5 %>
  <% else %>
    <% col_width = (col_width == 7 ? 5 : 7) %>
  <% end %>
  <% col_counter += col_width %>
<% end %>
<!-- PACKERY ------------------------------------------------------------->
<br>

<div id="packery-video-container">


  <% @videos.each do |video| %>
		
		<div class="packery-video-item bourbon-packery-video-card" style="padding-top: 0px">
			<div class="packery-item-overlay">
       		    <div class="article-image-container">
                  <% if video.video_thumbnail %>
			  		<%= link_to(image_tag(video.video_thumbnail, class: 'article-image article-image-margin', :style => 'padding:0px;margin-bottom:5px;' ), video_upload_path(video), title: video.title) %>
	    	      <% end %>
                </div>
	    	    <div class="article-title ">
	          		<%= link_to video.title.upcase, video_upload_path(video), title: video.title.titleize, class:'title-color' %>
	       	    </div>
	       	<!--<div class="article-subtitle">
	       			<%#= link_to(ActionView::Base.full_sanitizer.sanitize(video.description).html_safe.upcase.truncate(120), video_upload_path(video), title: video.title.titleize, class:'subtitle-color') %>
	       		</div>-->
	       	<!--<div class="article-comments">
	       			<% comment_number = ['12', '5', '8', '19', '21', '3', '17'] %>
	      			<%= link_to image_tag("../assets/comment_bubble.png", :alt => "comments", :width => 30, :height => 30) %> <%= comment_number.sample %>
	      		</div>
	      		<div class="article-bookmark">
	        		<%= link_to image_tag("../assets/bookmark.png", :alt => "comments", :width => 15, :height => 20) %>
	        </div>-->
	        </div>
		</div>
		 
	<% end %>
		
</div>

<script>

jQuery(document).ready(function($) {
    var $container = $('#packery-video-container');
    imagesLoaded( $container, function() {
        $container.packery({
            itemSelector: '.packery-video-item',
 			gutter: 10,
        });
    });
});

</script>

app/views/welcome/admin.html.haml
.row
  .col-md-12
    .page-header
      %h1 Admin Page
      %p.lead This is the landing page for system admins

      .btn-group
        .btn-group
          %button.btn.btn-default.dropdown-toggle{type: 'button', data: {toggle: 'dropdown'}}
            Manage Bourbon Media and Content
            %span.caret
          %ul.dropdown-menu{role: 'menu'}
            %li
              =link_to 'Media Uploads', media_uploads_url
            %li
              =link_to 'Profile Questions', profile_questions_url
            %li
              =link_to 'Question Categories', profile_question_categories_url
            %li
              =link_to 'User Invitations', user_invites_url
          .btn-group
            %button.btn.btn-default.dropdown-toggle{type: 'button', data: {toggle: 'dropdown'}}
              Manage Bourbon Users
              %span.caret
            %ul.dropdown-menu{role: 'menu'}
              %li
                =link_to 'Users', users_url
              %li
                =link_to 'User groups', user_groups_url
              %li
                =link_to 'Countries', countries_url



.row
  .col-sm-12
    %p
      Landing page for:
      =link_to 'Anonymous users', welcome_landing_url(force: 'yes'), class: 'btn btn-info btn-sm'
      =link_to 'Standard users', welcome_normal_user_url, class: 'btn btn-info btn-sm'
      =link_to 'Contributors', welcome_contributor_url, class: 'btn btn-info btn-sm'
      =link_to 'Curators', welcome_curator_url, class: 'btn btn-info btn-sm'
      =link_to 'Admins', welcome_admin_url, class: 'btn btn-info btn-sm'
.row
  .col-md-2
    .well.well-sm.text-center
      %h2=@user_all
      %p=link_to('users registered', users_url)
  .col-md-2
    .well.well-sm.text-center
      %h2=@media_uploads_all
      %p=link_to('media uploads', media_uploads_url)
  .col-md-2
    .well.well-sm.text-center
      %h2=@bourbon_articles_all
      %p=link_to('articles', stories_url)

app/views/welcome/contributor.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Dashboard</h1>
    </div>
  </div>
</div>
    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
          <h1>Articles</h1>
        </div>
      </div>
    </div>
<div class="row">
  <div class="col-md-12">
    <ul class="dashboard-tabs">
      <li class="active">
        <a data-toggle="tab" href="#wip_articles">Work in progress</a>
      </li>
      <li>
        <a data-toggle="tab" href="#being_reviewed"> Being reviewed</a>
      </li>
      <li>
        <a data-toggle="tab" href="#published"> Published</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active fade in" id="wip_articles">
        <%= render partial: 'bourbon_articles/index', locals: {the_articles: @bourbon_articles.saved_as_draft.all_in_order} %>
      </div>
      <div class="tab-pane fade" id="being_reviewed">
        <%= render partial: 'bourbon_articles/index', locals: {the_articles: @bourbon_articles.sent_for_review.all_in_order} %>
      </div>
      <div class="tab-pane fade" id="published">
        <%= render partial: 'bourbon_articles/index', locals: {the_articles: @bourbon_articles.published.all_in_order} %>
      </div>
    </div>
  </div>
</div>
<% if current_user.admin? %>
    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
          <h1>Videos</h1>
        </div>
      </div>
    </div>
    <div class="row">

    <div class="container">
      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-9 col-centered-packery">
          <div class="row">
            <table border="1" style="width:100%">
          <thead>
          <tr>
          <th>Title</th>
          <th>Created</th>
          <th></th>
          <th></th>
          </tr>
          </thead>
          <tbody>
          <% @videos.each do |video| %>
          <tr>
            <th><%= video.title %></th>
            <th><%= video.created_at.to_s(:standard) %></th>
            <th><%= link_to 'Show', video_upload_path(video), class: 'btn btn-default dashboard-btn' %></th>
            <th><%= link_to 'Edit', edit_video_upload_path(video), class: 'btn btn-default dashboard-btn' %></th>
            <th><%= link_to 'Delete', video, method: :delete, class: 'btn btn-default dashboard-btn' %></th>
          </tr>
          <% end %>
          </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    </div>
<% end %>
<!-- commented out section as only article functionality works and is duplicated above -->
 <%# if current_user.curator? %>
  <!-- <hr/> -->
  <%#= render partial: 'welcome/curator_stuff', locals: {curated_articles: @curated_articles} %>
<%# end %>

app/views/welcome/curator.html.haml
.row
  .col-md-12
    .page-header
      %h1 Curators
      %p.lead Everything you need to be a curator

=render partial: 'welcome/curator_stuff', locals: {curated_articles: @bourbon_articles}

app/views/welcome/landing.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-9 col-centered-packery">
      <div class="row">
      <br>
      <div class="related-title-landing"><%= link_to 'Stories', stories_url %></div>  
      <br>
        <%= render partial: 'welcome/stories_grid', locals: {bourbon_articles: @bourbon_articles} %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-9 col-centered-packery">
      <div class="row">
      <br>
      <div class="related-title-landing"><%= link_to 'Videos', video_uploads_url %></div>  
      <br>
        <%= render partial: 'welcome/videos_grid', locals: {videos: @videos} %>
      </div>
    </div>
  </div>

</div>

app/views/welcome/landing.html.haml
-#content_for :jumbotron do
  .jumbotron.text-center
    %h1 Landing Page
    %h1 welcome

.container
  .row
    .col-sm-8.col-sm-offset-2
      %h1.page-header.text-center Welcome to Bourbon
  .row
    .col-sm-8.col-sm-offset-2
      .row
        =render partial: 'welcome/stories_grid', locals: {bourbon_articles: @bourbon_articles}

app/views/welcome/normal_user.html.haml
.row
  .col-md-12
    .page-header
      %h1 Welcome#normal_user
      %p.lead Content for normal users that are logged in
.row
  .col-sm-9
    -if @bourbon_articles.size > 0
      .jumbotron{style: (@bourbon_articles.first.image ? "background: #fff url('" + @bourbon_articles.first.image.try(:upload).try(:url).to_s + "') no-repeat center center !important;" : '') + (@bourbon_articles.first.try(:image).try(:make_text_bright) ? 'color: #eee;' : '')}
        %h1=@bourbon_articles.first.article_title
        %p.lead=@bourbon_articles.first.article_subtitle
        %p=@bourbon_articles.first.article_body.split("\r")[0]
        %p=link_to 'read more', @bourbon_articles.first

      -if @bourbon_articles.size > 1
        .row
          -@bourbon_articles[1..-1].each do |bourbon_article|
            .col-sm-4.text-center
              -filename = bourbon_article.image.try(:upload).try(:url, :square).to_s
              =image_tag(filename, class: 'img-circle', data: {src: 'holder.js/140x140'}, alt: bourbon_article.image.try(:alt_tag))
              %h2=bourbon_article.article_title
              %p=bourbon_article.article_subtitle
              %p=link_to 'read more', bourbon_article, class: 'btn btn-default'
  .col-sm-3
    =render partial: 'profile_question_answers/ask'

app/views/welcome/people.html.haml
.row
  .page-header.text-center
    %h1 People
    -if params[:tag]
      %p.leader
        tag:
        %span.btn.btn-xs.btn-success=params[:tag].to_s
        =link_to 'x', welcome_people_url, title: 'reset', class: 'btn btn-xs btn-default'

-col_counter = 0
.row
  -@users.each do |user|
    -if col_counter >= 12
      ="</div><div class='row'>".html_safe
      -col_counter = 0
    -col_counter += 4
    .col-sm-4.people-mini-view
      =link_to user_image(user, size: 330, class: 'img-rounded'), profile_path(user.url_code)
      %h3.name=link_to user.full_name, profile_path(user.url_code)
      %p.text-muted
        -if user.location
          =link_to((user.location + ','), profile_path(user.url_code))
        =link_to user.country.name, profile_path(user.url_code)
        %br/
        -user.tags.to_s.split(',').each do |tag|
          =link_to tag.strip, welcome_people_url(tag: tag.strip), class: 'btn btn-xs btn-success'

app/views/welcome/search.html.haml
.row
  .col-md-12
    .page-header
      -if @search_results.size > 0
        %h1
          Your search generated
          =pluralize(@search_results.count, 'result') + ':'
      -else
        %h1 Nothing found: try again...
      .lead
        =form_tag(search_request_url) do
          =text_field_tag :search_for_this, params[:search_for_this], placeholder: 'search...', onblur: 'this.form.submit(); return false;'
.row
  .col-md-12
    -@search_results.each do |one_result|
      .well.one-result
        =link_to truncate(one_result[:name], length: 50), one_result[:url], class: 'text-success'
        .text-info=link_to 'http://localhost:3000' + truncate(one_result[:url], length: 50), one_result[:url]
        .text-muted=truncate(one_result[:description], length: 150)

app/views/welcome/tag_search.html.haml
.row
  .col-md-12
    .page-header
      -if @tag_search_results.size > 0
        %h1
          Tag Search:
          =pluralize(@tag_search_results.count, 'match')
          found

.row
  .col-md-12
    -@tag_search_results.each do |one_result|
      .well.one-result
        =link_to truncate(one_result[:name], length: 50), one_result[:url], class: 'text-success'
        .text-info=link_to truncate(one_result[:url], length: 50), one_result[:url]
        .text-muted=truncate(one_result[:description], length: 150)

app/views/welcome/video.html.erb
<!-- Cards for Stories tab //////////////////////////////////////////////////// -->
		
<!-- row 1 -->
<div class="row">
  <div class="[ col-xs-12 col-sm-8 col-md-8]">
  		<div class="[ info-card ] nohover">

<iframe src="//fast.wistia.net/embed/iframe/vfqcxhw9tz?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="388"></iframe><script src="//fast.wistia.net/assets/external/E-v1.js"></script>
	</DIV>
  </div>

<div class="[ col-xs-12 col-sm-4 col-md-4]">
	<div class="[ info-card ] nohover">
		<iframe src="//fast.wistia.net/embed/iframe/ulsbc47528?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="320" height="180"></iframe><script src="//fast.wistia.net/assets/external/E-v1.js"></script>
	</div>
</div>	
</div>		
		<!-- end row 1 -->